export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const LOGIN = 'LOGIN';
export const ADD_ERRORS = 'ADD_ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';

export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';
export const CREATE_USER_COMPLETED = 'CREATE_USER_COMPLETED';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';